name: SolarSystem
on:
    push:
        branches: 
            - main
            - 'feature/*'
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        env:
            MONGO_URI: ${{ vars.MONGO_URI }}
            MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6

            - name: Setup Nodejs Environment
              uses: actions/setup-node@v7
              with:
                node-version: '24.21.0'
                cache: npm

            - name: Cache npm Repository
              uses: actions/cache@v6
              with:
                path: 'node_modules'
                key: node-modules-${{ hashFiles('package-lock.json') }}
            
            - name: Install Dependency
              run: npm install

            - name: Run Unit test case
              run: npm test

            - name: list the files and folder
              run: |
                sudo apt-get update && sudo apt-get install -y tree
                tree -L 3 -I 'node_modules'

            - name: Check if any file named test-results.xml exist or not
              run: |
                if [ -f test-results.xml ]
                then
                  echo "file exist"
                else
                  echo "file doesn't exist"
                fi

            - name: Archive test test-results.xml
              uses: actions/upload-artifact@v7
              with:
                name: Mocha-Test-Result
                path: test-results.xml
                if-no-files-found: ignore


    code-coverage:
      name: Code Coverage
      runs-on: ubuntu-latest
      continue-on-error: true
      env:
            MONGO_URI: ${{ vars.MONGO_URI }}
            MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      steps:
        - name: checkout the Repository
          uses: actions/checkout@v6

        - name: Setup Node js
          uses: actions/setup-node@v7

        - name: Cache npm Repository
          uses: actions/cache@v6
          with:
            path: 'node_modules'
            key: node-modules-${{ hashFiles('package-lock.json') }}

        - name: Install Dependency
          run: npm install

        - name: Start the code coverage 
          run: npm run coverage

        - name: Archive coverage Repository
          if: always()
          uses: actions/upload-artifact@v7
          with:
            name: Code coverage report
            path: coverage
            retention-days: 5

    containerization:
      needs: [unit-testing, code-coverage]
      name: containerization
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the Repository
          uses: actions/checkout@v6
        
        - name: Login into Docker hub
          uses: docker/login-action@v4
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Build and push image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: om6214/solarsystem:${{ github.sha }}